--- # Test configurations
Initial Variables:
  t: 0
  dy: 20
  dx: 100
  
Parameters:
  - t: 0
  - x: 10
  - dy: 30
  
Conditions:
  - Ground Impact: y<-0.1
  - Final time: t=10
  - Too far: x>100
  - TerminalTest:
      union: and
      conditions:
      - Ground Impact
      - Final time
  - NestedTest:
      union: nor
      conditions:
      - TerminalTest
      - Too far
  - Apogee: y is local max
  - Terminal:
      union: or
      conditions:
      - Ground Impact
      - Final time
    
Terminal Condition: Terminal

Run Settings:
  propagator: explicit
  timestep: 0.1

Outputs:
  - id: 1
    title: X pos
    variable1: x
    plot type: Value at Condition
    condition: Terminal
    output type: text
  - id: 2
    title: Final time
    variable1: t
    plot type: Value at Condition
    condition: Terminal
    output type: text
  - id: 3
    title: Traj
    variable1: x
    variable2: y
    plot type: 2 Var along Trajectory
    output type: plot
  - id: 4
    title: Traj2
    variable1: y
    variable2: t
    plot type: 2 Var along Trajectory
    output type: plot
  - id: 5
    title: Apogee range
    variable1: x
    plot type: Value at Condition
    output type: text
    condition: Apogee


