--- # Test configurations
Initial Variables:
  t: 0
  dy: 20
  dx: 100
  
Run Variants:
  MC Variants:
  - paramID: default.y
    nominal: 0
    distribution: uniform
    min: 0
    max: 5
  
  Trade Variants:
  - One:
      default.x: 0
      default.dx: 30
      default.dy: 50
  - Two:
      default.x: 5
      default.dx: 29.6
      default.dy: 49
  - Three:
      default.x: 10
      default.dx: 29.2
      default.dy: 48
  - Four:
      default.x: 15
      default.dx: 28.8
      default.dy: 47
  - Five:
      default.x: 20
      default.dx: 28.4
      default.dy: 45.9
  - Six:
      default.x: 25
      default.dx: 28.0
      default.dy: 44.8
  - Seven:
      default.x: 30
      default.dx: 27.6
      default.dy: 43.7
  - Eight:
      default.x: 35
      default.dx: 27.2
      default.dy: 42.6
  - Nine:
      default.x: 40
      default.dx: 26.7
      default.dy: 41.4
#  - paramID: default.vehiclePointMass
#    nominal: off
#    tradeValues:
#    - on
#    - on
#    - off
#  - paramID: default.centralBody
#    nominal: Mars
#    tradeValues:
#    - Earth
#    - Venus
#    - Sol
    
  Single Variants:
  - paramID: default.t
    nominal: 3.0
  
Conditions:
  - Ground Impact: y=0
  - Final time: t>2.0
  - Too far: x>100
  - TerminalTest:
      union: and
      conditions:
      - Ground Impact
      - Final time
  - NestedTest:
      union: nor
      conditions:
      - TerminalTest
      - Too far
  - Apogee: local max y
  - Terminal:
      union: and
      conditions:
      - Ground Impact
      - Final time
    
Terminal Condition: Terminal

Run Settings:
  propagator: explicit
  timestep: 0.1

Outputs:
  - id: 1
    title: X pos
    variable1: x
    plot type: Value at Condition
    condition: Terminal
    output type: text
  - id: 2
    title: Final time
    variable1: t
    plot type: Value at Condition
    condition: Terminal
    output type: text
  - id: 3
    title: Traj
    variable1: x
    variable2: y
    plot type: 2 Var along Trajectory, by Category
    output type: plot
  - id: 4
    title: Traj2
    variable1: y
    variable2: t
    plot type: 2 Var along Trajectory
    output type: plot
  - id: 5
    title: Apogee range
    variable1: x
    plot type: Value at Condition
    output type: text
    condition: Apogee

Physics Settings:
  physicsModel: Flat Surface, 3D
  vehiclePointMass: true

