--- # Test configurations
Initial Variables:
  t: 0
  dy: 20
  dx: 100
  
Parameters:
  - t: 0
  - x: 10
  - dy: 30
  
Conditions:
  - Ground Impact: y<-0.1
  - Final time: t>10
  - Too far: x>100
  - TerminalTest:
    union: and
    conditions:
    - Ground Impact
    - Final time
  - NestedTest:
    union: nor
    conditions:
    - TerminalTest
    - Too far
    
Terminal Condition:
  union: or
  conditions:
  - Ground Impact
  - Final time
  
Outputs:
  - id: 1
    title: X pos
    variable: x
    plot type: Single Value
    condition: terminal
    output type: text
  - id: 2
    title: Final time
    variable: t
    plot type: Single Value
    condition: terminal
    output type: text
  - id: 3
    title: Traj
    variable1: x
    variable2: y
    plot type: 2 Var, along Trajectory
    output type: plot
  - id: 4
    title: Traj2
    variable1: y
    variable2: t
    plot type: 2 Var, along Trajectory
    output type: plot


